[package]
name = "client-proxy"
version = "0.1.0"
authors = ["HunterSun2008 <sht@palliums.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proptest = "0.9.2"
client = { path = "/home/hunter/Projects/work/libra/client" }

[target.'cfg(target_os="android")'.dependencies]
# change this directory for the path of Libra client 
jni = { version = "0.13.1", default-features = false }

[lib]
crate-type = ["cdylib"]