[package]
name = "client-proxy"
version = "0.1.0"
authors = ["HunterSun2008 <sht@palliums.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
# change this directory for the path of Libra client 
client = { path = "/home/hunter/libra/client", version = "0.1.0" } 
libra-types = { path = "/home/hunter/libra/types" }
compiler = { path = "/home/hunter/libra/language/compiler"  }
bytecode-verifier = { path = "/home/hunter/libra/language/bytecode-verifier", version = "0.1.0" }
ir-to-bytecode = { path = "/home/hunter/libra/language/compiler/ir-to-bytecode", version = "0.1.0" }
bytecode-source-map = { path = "/home/hunter/libra/language/compiler/bytecode-source-map", version = "0.1.0" }
stdlib = { path = "/home/hunter/libra/language/stdlib", version = "0.1.0" }
vm = { path = "/home/hunter/libra/language/vm", version = "0.1.0" }
transaction-builder = { path = "/home/hunter/libra/language/transaction-builder", version = "0.1.0" }
lcs = { path = "/home/hunter/libra/common/lcs", version = "0.1.0", package = "libra-canonical-serialization" }

serde_json = "1.0.40"
serde = { version = "1.0.99", default-features = false }
lazy_static = { version = "1.3.0", default-features = false }
hex = "0.3.2"
libc = "0.2"
tempdir = "0.3.7"
anyhow = "1.0"
#failure = "0.1.3"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.13.1", default-features = false }

[target.'cfg(target_os="wasm")'.dependencies]
wasm-bindgen = "0.2"


[profile.release]
#abort
panic = "unwind" 
