[package]
name = "client-proxy"
version = "0.1.0"
authors = ["HunterSun2008 <sht@palliums.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
# change this directory for the path of Libra client 
client = { path = "/home/hunter/Projects/work/libra/client" } 
libra-types = { path = "/home/hunter/Projects/work/libra/types" }
compiler = { path = "/home/hunter/Projects/work/libra/language/compiler"  }

hex = "0.3.2"
libc = "0.2"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.13.1", default-features = false }

[target.'cfg(target_os="wasm")'.dependencies]
wasm-bindgen = "0.2"


[profile.release]
#abort
panic = "unwind" 
